config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              :controllers => {
                :omniauth_callbacks => "users/omniauth_callbacks"
              }

  # allow front end angularjs to get current_user and check for user
  devise_scope:user do
    get '/api/current_user' => 'users/sessions#show_current_user'
    post '/api/check/is_user' => 'users/users#is_user', as: 'is_user'
    post '/api/check/is_admin' => 'users/users#is_admin', as: 'is_admin'
  end

  root 'home#index'

  # HANDLE VCODER FRONT
  post 'contact_us' => 'home#contact_us', as: :contact_us
  get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
  get 'faq' => 'home#faq', as: :faq
  get 'tuition' => 'home#tuition', as: :tuition
  get 'curriculum' => 'home#curriculum', as: :curriculum
  get 'the_program' => 'home#the_program', as: :the_program

  resources :prospects do
    collection do
      get :thank_you
    end
  end

  resources :cohorts

  resources :students

  resources :announcements
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :contact_us, :privacy_policy, :faq, :tuition, :the_program, :curriculum]
  layout :choose_layout

  def index
    unset_footer
  end

  def contact_us
    UserMailer.contact_us(params).deliver
    render :json => {data: "We have received your enquiry and will respond to you within 24 hours."}
  end

  def privacy_policy
  end

  def faq
  end

  def tuition
    @cohorts = Cohort.where("status = ?", Cohort::STATUS_ENROLLING)
                      .order("start_at DESC")
                      .take(2)

  end

  def the_program
  end

  def curriculum
  end

  def choose_layout
    user_signed_in? ? "angular" : "application"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/curriculum.html.erb
<% content_for(:title, 'Curriculum')%>

<div class="small-12 large-12 columns top-bg">
  <div class="small-12 large-10 large-offset-1 columns" id="curriculum">
    <div class="small-8 large-12 columns text-center">
      <h1 class="x2-margin-top apply-text text-dark-blue text-center" id="curri">
        CURRICULUM
      </h1>
    </div>
    <div class="small-12 large-12 columns">
    <ul class="timeline">
      <li class="event">
        <input type="radio" name="tl-group" class="tl-input" checked/>
        <label></label>
        <div class="thumb week-1"><span>Week 1:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>HTML5 & CSS3 Basic</h3>
              <ul>
                <li>Basic Terminology</li>
                <li>My first website</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-2"><span>Week 2:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>My favorite website</h3>
              <ul><li>Clone a website with HTML & CSS</li></ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-3"><span>Week 3:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>Introduction to Ruby Basics</h3>
              <ul>
                <li>Ruby syntax</li>
                <li>Numbers, String, Boolean</li>
                <li>Variable, Math, Flow Control etc.</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-4"><span>Week 4:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>Ruby Basics II</h3>
              <ul>
                <li>Data Structure</li>
                <li>Method, Class, Block</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-5"><span>Week 5:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>Intermediate + Advanced Ruby</h3>
              <ul>
                <li>My Cash Register</li>
                <li>Banking</li>
                <li>Comet</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-67"><span>Week 6-7:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>Object Oriented Programming</h3>
              <ul>
                <li>Class, Class Method, Private Method</li>
                <li>Module</li>
                <li>File I/O</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-8"><span>Week 8:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>SQL</h3>
              <ul>
                <li>Create Table</li>
                <li>Insert, Update, Delete</li>
                <li>Advanced Queries</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-9"><span>Week 9:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>Web Development With Ruby on Rails</h3>
              <ul>
                <li>Git - Github</li>
                <li>The HTTP protocol</li>
                <li>Routing</li>
                <li>Model - View - Controller (MVC)</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-10"><span>Week 10:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>Migration, Debugging, TDD, Deploy to Heroku</h3>
              <ul>
                <li>Schema Design</li>
                <li>Indexing</li>
                <li>ActiveRecord</li>
                <li>Debug with Pry</li>
                <li>Test Driven Developemnt (TDD)</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-11"><span>Week 11:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>Front End</h3>
              <ul>
                <li>Twitter Boostrap / Foundation</li>
                <li>Jquery</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-1215"><span>Week 12 - 15:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>Group Project</h3>
              <ul>
                <li>Eager Load, Lazy Load</li>
                <li>Ajax, JSON</li>
                <li>Authentication</li>
                <li>Pagination</li>
                <li>ActionMailer + E-Mail</li>
                <li><strong>Interview Preparation + Practice</strong></li>
              </ul>
            </div>
          </div>
        </div>
      </li>

      <li class="event">
        <input type="radio" name="tl-group" class="tl-input"/>
        <label></label>
        <div class="thumb week-1620"><br><span>Week 16 - 20:</span></div>
        <div class="content-perspective">
          <div class="content">
            <div class="content-inner">
              <h3>VCoder Final Project</h3>
              <ul>
                <li>Building an application with complexity</li>
                <li>Project will be used in porfolio.</li>
                <li>Code Quality</li>
              </ul>
            </div>
          </div>
        </div>
      </li>

    </ul>
  </div>
</div>

app/views/home/faq.html.erb
<% content_for(:title, 'FAQ')%>

<div class="container">
  <div class="row panel white-bg x2-margin-top panel-radius">
    <div>
      <h1 class="x2-margin-top apply-text text-dark-grey text-center ">
        FREQUENTLY ASKED QUESTIONS
      </h1>
      <div class="small-12 large-12 columns x2-margin-top nopadding"
            id="faq">
        <dl class="accordion" data-accordion>
          <dd class="accordion-navigation">
            <a href="#panel1b"><span class="plusminus icon-space-right">+ </span>What is Vcoder Bootcamp?</a>
            <div id="panel1b" class="content padding">
             Vcoder bootcamp is a unique 20 week fully imersive course that takes eager learners from little to no experience and teach them what it takes to add value as a junior contributor to a software engineering team.
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel2b"><span class="plusminus icon-space-right">+ </span>What makes Vcoder Bootcamp different from similar programs?</a>
            <div id="panel2b" class="content">
             Vcoder bootcamp sets itself apart from similar programs via its long term focus on the students' success after completing the course. We are not concerned about how many people we have as students rather what great things our students are doing after they graduate. Many similar programs today are either student self­ taught online courses or full on commitment at an onsite location. Here at Vcoder Bootcamp we have merged the two methods to create a unique course to give our students the commitment and support they need as well as flexibility.Unlike, online programs, <strong>we offer our students at least 15 hours of support a week </strong> where they can <strong>directly talk to mentors and get unlimited help onsite or online </strong>. Traditional online programs only offer up 4 hours a week and is focused more on student self learning. Importantly, Vcoder Bootcamp provides a post course completition support where students can continue to drop in­person during office hours or via online to get the help they need to ensure emotional and job­specific support during the initial phase of their new jobs.
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel3b"><span class="plusminus icon-space-right">+ </span>Is this course the same thing as school, but for coding?</a>
            <div id="panel3b" class="content">
              No, it is probably the opposite of it becausing running our bootcamp like school would be very unproductive and hmm.. what is a polite way of saying this, boring. Vcoder Bootcamp sets itself apart from typical school courses is that we will actually be doing something. Students will be able to learn and apply the skills to build REAL things. Some of the things our students build may follow them into their portfolio or even to their next job, that's how real they will be. It's not about sitting in a classroom to listen to lecture about how to code, but actually practice to learn these skills. Vcoder Bootcamp teaches strong basics so that students learn to build, build, and kee building from there. Don't think that you will learn the same thing over and over again, because we will throw new challenges at you everyday, until you can build cool projects that have always lingered in your head.
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel4b"><span class="plusminus icon-space-right">+ </span>What are the technical qualifications?</a>
            <div id="panel4b" class="content">
              ­No prior industry or academic experience is required. Yes, that means you don't need to have a computer science degree or background to become a developer! We teach everything from scratch in a easy step by step process. The only thing we want to make sure is that you've turned on a computer at some point in your lives and done some non-programming tasks. That's not too much to ask for right?
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel5b"><span class="plusminus icon-space-right">+ </span>What are the non­technical qualifications?</a>
            <div id="panel5b" class="content">
              ­<ul>
                <li>Passionate, eager learners.</li>
                <li>Empathetic communicators ­ we care about people more than machines and their ability to empathize with one another as a team.</li>
                <li>Dedicated, curious coders who value building beautiful and meaningful things.</li>
              </ul>
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel6b"><span class="plusminus icon-space-right">+ </span>Who is the typical Vcoder Bootcamp applicant?</a>
            <div id="panel6b" class="content">
              ­Using the word "typical" goes against what Vcoder Bootcamp is about and what we look for in applicants. Vcoder Bootcamp is all about looking for diversed people with different backgrounds. Some applicants may have CS degrees and want to get web dev­specific training before applying to jobs. Some come from adjacent fields, like design or IT, and have been tangentially working with coding for a while. Some have been learning programming on their own, and wanted to get the complete skill set they needed to start a dev career. We look for passionate and eager learners ready to build awesome projects!
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel7b"><span class="plusminus icon-space-right">+ </span>Do you accept foreign students?</a>
            <div id="panel7b" class="content">
              ­Definately! Here at Vcoder Bootcamp not only embrace diversity, but also encourage it at all levels. We, unfortunately, do not offer visa assistance.
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel8b"><span class="plusminus icon-space-right">+ </span>What's the schedule?</a>
            <div id="panel8b" class="content">
              ­The weekly schedule is as following:
              <ul>
                <li>Our "week" starts from <strong>Saturday (1pm-5pm)</strong>, where lecture will be taken place in approximately 30 to 60 minutes. Students will immediately dive into project right after.</li>
                <li><strong>Sunday (1pm-5pm)</strong> the "Batte Ship Day", students will form groups, apply the material learned from Saturday to work on a "real" projects and try to deploy it during the day. We will also vote to see which team perform best and do some code reviews.<br>
                At the end of day, there will be some fun activites to engage everyone and build relationships between Vcoders.
                Light beverages and foods will be provided by the house.</li>
                <li><strong>Tuesday & Thursday (6pm-9pm):</strong> Each group's mentor will assign some tasks which need to be complete during the week. These assignment are not mendatory but recommended to help us track student's learning and provide help as needed. Students can choose to work onsite with mentor or online at our forum and help center.</li>
                <li><strong>Unlimited help via email and forum daily to fit in your schedule.</strong></li>
              </ul>
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel9b"><span class="plusminus icon-space-right">+ </span>Do I need to bring a laptop?</a>
            <div id="panel9b" class="content">
              Absolutely! All of our students will need to bring their own Mac laptops. We require our students to bring a Mac because running open source softwares on a windows machine may be very difficult. We want our students to easily work and learn how it would be on their real job. Don't worry if you don't know how to do that, we will spend some time figuring all this out during on site meetings. Everyone will have consistent tools and softwares to make collaboration and troubleshooting much easier.
              We provide some monitor displays for students to hook their laptops up to for pair programming for coding challenges or group projects.
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel10b"><span class="plusminus icon-space-right">+ </span> When should I apply to get into a particular cohort?</a>
            <div id="panel10b" class="content">
              Students should apply when they feel they are ready to start the journey. It is never too early to apply.
              There is no deadline to apply as long as its before the given cohort start date. If we think you are a great fit with our program, we will set up an interview. Class fills up when we have admit enough qualified students.
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel11b"><span class="plusminus icon-space-right">+ </span> How do I find out more about applying?</a>
            <div id="panel11b" class="content">
              You can send an email to admissions@vcoderbootcamp.com
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel12b"><span class="plusminus icon-space-right">+ </span> Are there loan options?</a>
            <div id="panel12b" class="content">
              In terms of student loans, we have not been able to jump through the necessary bureaucratic hoops to qualify for federally­subsidized education programs, etc.
              However, we do offer two tuition options. One being, pay tuition upfront. The other option would be personal monthly payments through Voderbootcamp. Monthly payments will be divided into 5 months during the bootcamp of $400.00/month (pay as you go) to cover tuition cost.
            </div>
          </dd>
          <dd class="accordion-navigation">
            <a href="#panel13b"><span class="plusminus icon-space-right">+ </span>I have more questions...</a>
            <div id="panel13b" class="content">
              Shoot us an Email ­ <strong>help@vcoderbootcamp.com</strong>.
              <p>The Skills you pick up here are valuable around the world. Graduates walk out the door with an increasingly impressive array of project work that would impress employers in any country.</p>
            </div>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="top-center">
  <div class="small-12 medium-12 large-8 large-offset-2 columns welcome-text">
    <div class="small-12 large-12 columns field-man">
      Full-Stack Web Development with Ruby on Rails
    </div>
    <div class="small-12 large-12 columns">
      <div class="small-12 medium-4 large-4 columns">
        <div class="panel panel-radius custom-panel hp-panel"
              id="first-pan">
          <h5 class="welcome-page-h5">Front End</h5>
          <%= image_tag "bootstrap-jquery-html5-css3.png" %>
        </div>
      </div>
      <div class="small-12 medium-4 large-4 columns">
        <div class="panel panel-radius custom-panel hp-panel">
          <h5 class="welcome-page-h5">Back End</h5>
          <div>
            <div class="small-6 large-6 columns">
              <%= image_tag "ruby-logo.png" %>
            </div>
            <div class="small-6 large-6 columns">
              <%= image_tag "rails.png" %>
            </div>
          </div>
          <div>
            <%= image_tag "postgresql-logo.png" %>
          </div>
        </div>
      </div>
      <div class="small-12 medium-4 large-4 columns">
        <div class="panel panel-radius custom-panel hp-panel">
          <h5 class="welcome-page-h5">Tools</h5>
            <div class="row">
              <div class="small-6 large-6 columns">
                <%= image_tag "github.png" %>
                <div>GitHub</div>
              </div>
              <div class="small-6 large-6 columns">
                <%= image_tag "heroku.png" %>
                <div>Heroku</div>
              </div>
            </div>
        </div>
      </div>
    </div>
    <div class="small-12 large-12 columns text-center">
      <a href="<%= new_prospect_path %>"
        class="small-12 large-6 button radius"
        id="start-application">
        START AN APPLICATION</a>
    </div>
  </div>
</div>
<div class="small-12 large-12 columns zigzag container2">
  <div class="small-12 large-10 large-offset-1 columns x2-margin-top x2-margin-bottom text-center">
    <h2 class="why-should--headline">Why Should You Choose This Course</h2>
    <div class="small-12 large-12 columns">
      <div class="small-12 large-4 columns text-center">
        <%= image_tag "realapp.jpeg", alt: "Build real time app",
                                    class: "avatar avatar--medium" %>
        <div class="small-12 columns x2-margin-top">
          <h4 class="avatar-header">Build Real Application</h4>
          <p class="sub-avatar">Through hands on projects, we train you how to work individually as well as pair programming, applying agile methodology and test driven development to deploy industry level web applications.</p>
        </div>
      </div>
      <div class="small-12 large-4 columns text-center">
        <%= image_tag "hybridclass.jpeg", alt: "The Best of Both World - Hybrid Class", class: "avatar avatar--medium" %>
        <div class="small-12 columns x2-margin-top">
          <h4 class="avatar-header">The Best of Both World  - Hybrid Class</h4>
          <ul class="ul--no-decor sub-avatar">
            <li>Online Video</li>
            <li>On-Site Lecture</li>
            <li>NO prior programming experience needed</li>
          </ul>
        </div>
      </div>
      <div class="small-12 large-4 columns text-center">
        <%= image_tag "support.jpeg", alt: "Unlimited support",
                                    class: "avatar avatar--medium" %>
        <div class="small-12 columns x2-margin-top">
          <h4 class="avatar-header">Unlimited Support</h4>
          <ul class="ul--no-decor sub-avatar">
            <li>Up to 15 hours on-site mentorship/week</li>
            <li>Daily support via email/forum</li>
            <li></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="small-12 large-12 columns text-center">
      <%= image_tag "five_stars.png", alt: "Five Stars Quality", style: "  height: 30px;" %>
      <div id="satisfaction"> 100% Satisfaction Guaranteed</div>
    </div>
  </div>
</div>
<div class="small-12 large-12 columns nopadding text-center" id="community">
  <%= image_tag "friends.jpeg", alt: "Life Time Experience" %>
  <div class="small-12 large-5 columns">
    <span class="rotate text-rotate">
      "Life-Time Relationship With Other Passionate Vcoders" | "Supportive And Health-Oriented Environment, ALWAYS" | "Actively Engage In Local Meetups And Activites" | "APPLY NOW"
    </span>
  </div>
</div>
<footer class="small-12 large-12 columns l-footer">
  <div class="small-12 large-6 columns x2-margin-top">
    <div class="small-6 large-6 columns nopadding">
      <ul class="ul--no-decor foot-nav foot-nav-link">
        <h4 class="text-grey">Prospective Students</h4>
        <li>
          <i class="fa fa-check-square">
            <a href="<%= new_prospect_path %>" class='icon-space link--no-decor'>&nbsp;APPLY NOW</a>
          </i>
        </li>
        <li>
          <i class="fa fa-question-circle">
            <a href="<%= faq_path %>" class='icon-space link--no-decor'>&nbsp;&nbsp;FAQ</a></i>
        </li>
        <li>
          <i class="fa fa-unlock-alt">
            <a href="<%= privacy_policy_path %>" class='icon-space link--no-decor'>&nbsp;&nbsp;PRIVACY</a>
          </i>
        </li>
      </ul>
    </div>
    <div class="small-6 large-6 columns nopadding">
      <h4 class="text-grey icon-space">&nbsp;Connect</h4>
      <ul class="ul--no-decor foot-nav foot-nav-link">
        <li>
          <i class="fa fa-newspaper-o"><span class='icon-space'>BLOG</span></i>
        </li>
        <li>
          <i class="fa fa-facebook-square"><span class='icon-space'>FACEBOOK</span></i>
        </li>
        <li>
          <i class="fa fa-twitter-square"><span class='icon-space'>TWITTER</span></i>
        </li>
        <li>
          <i class="fa fa-google-plus"><span class='icon-space'>GOOGLE +</span></i>
        </li>
      </ul>
    </div>
    <div class="small-12 large-12 columns l-copyright" id="cp-right">
      <div class="text-white">© 2015 VCoder Bootcamp. All rights reserved.</div>
    </div>
  </div>
  <div class="small-12 large-6 columns">
    <div class="x2-margin-top">
      <h3 class="text-grey">
        <i class="fa fa-envelope"></i>&nbsp;Drop us a line and we'll be in touch shortly!
      </h3>
      <%= form_tag({}, {id: "contact-us-form",
                        method: "post",
                       "data-url" => contact_us_path,
                        class: "x2-margin-top form-ajax"}) do %>
        <%= text_field_tag 'name',
                            nil,
                            placeholder: 'Name',
                            :required => true %>
        <%= email_field_tag 'email',
                            nil,
                            placeholder: 'Email',
                            :required => true,
                            :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
        <%= text_area_tag 'messages',
                          nil, placeholder: "Message", rows: 3, cols: 25 %>
        <%= button_tag "Send", class: "small button small-3 right radius" %>
      <% end %>
    </div>
  </div>
</footer>

app/views/home/tuition.html.erb
<% content_for(:title, 'Tuiton')%>

<div class="container">
  <h1 class="x2-margin-top apply-text text-dark-grey text-center">
    TUITION
  </h1>
  <div class="row panel white-bg panel-radius">
    <div class="small-12 large-10 large-offset-1 columns">
      <% if @cohorts.present? %>
        <% @cohorts.reverse.each_with_index do |cohort, index| %>
          <%= render "cohorts/entity", view_mode: :div,
                                       entity: cohort,
                                       index: index %>
        <% end %>
      <% else %>
        Sorry, our class are full, please check back next time
      <% end %>
    </div>
    <div class="small-12 large-12 columns x2-margin-top text-center"
        id="tuiton-2nd">
      <div id="payment-choice"> We offer two payment plans — $1,850 upfront OR five payments of $400 per month.</div>
      <a href="<%= new_prospect_path %>" class="button medium button-orange radius">Enroll Now</a>
    </div>
  </div>

</div>