config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              :controllers => {
                :omniauth_callbacks => "users/omniauth_callbacks"
              }

  # allow front end angularjs to get current_user and check for user
  devise_scope:user do
    get '/api/current_user' => 'users/sessions#show_current_user'
    post '/api/check/is_user' => 'users/users#is_user', as: 'is_user'
    post '/api/check/is_admin' => 'users/users#is_admin', as: 'is_admin'
  end

  root 'home#index'

  # HANDLE VCODER FRONT
  post 'contact_us' => 'home#contact_us', as: :contact_us
  get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
  get 'faq' => 'home#faq', as: :faq
  get 'tuition' => 'home#tuition', as: :tuition
  get 'curriculum' => 'home#curriculum', as: :curriculum
  get 'the_program' => 'home#the_program', as: :the_program

  resources :prospects do
    collection do
      get :thank_you
    end
  end

  resources :cohorts

  resources :students

  resources :announcements
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  GENDER_MALE = "Male"
  GENDER_FEMALE = "Female"
  PAYMENT_TYPE_UP_FRONT = "Up Front"
  PAYMENT_TYPE_MONTHLY = "Monthly"

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, length: { maximum: 50 }
  validates :last_name, length: { maximum: 50 }
  validates :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :comment, length: { maximum: 1000 }
  validates :gender, inclusion: { in: %w(Male Female) }

  def self.gender_choices
    [[GENDER_MALE, GENDER_MALE],
    [GENDER_FEMALE, GENDER_FEMALE]]
  end

  def self.payment_types
    [[PAYMENT_TYPE_UP_FRONT, PAYMENT_TYPE_UP_FRONT],
    [PAYMENT_TYPE_MONTHLY, PAYMENT_TYPE_MONTHLY]]
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  def index
  end

  def new
    @prospect = Prospect.new
  end

  def create
    @prospect = Prospect.new(prospect_params)
    if @prospect.save
      redirect_to thank_you_prospects_path
    else
      flash[:succes] = "Please check your input for the error(s) below."
      render "new"
    end
  end

  def thank_you

  end

  private
  def prospect_params
    params.require(:prospect).permit(:first_name, :last_name, :gender,
                                    :email, :phone_number, :skype_id,
                                    :payment_type, :comment )
  end
end

app/views/prospects/new.html.erb
<% content_for(:title, 'Apply to Vcoder BootCamp')%>

<div class="container">
  <div class="row panel white-bg text-center x2-margin-top panel-radius">
    <div class="">
      <h1 class="x2-margin-top apply-text text-dark-grey">Apply To VCoder BootCamp</h1>
      <%= form_for @prospect, :url => prospects_path,:html => { method: "POST", class: "small-12 medium-10 medium-offset-1 columns x2-margin-top form--apply"} do |form| %>
        <div class="row collapse">
          <% if @prospect.errors.any? %>
          <ul class="ul--no-decor">
            <% @prospect.errors.full_messages.each do |msg| %>
              <li class="text-red"><%= msg %></li>
            <% end %>
          </ul>
          <% end %>
        </div>
        <%= form.text_field :first_name, :required => true, placeholder: 'First Name' %>
        <%= form.text_field :last_name, :required => true, placeholder: 'Last Name' %>
        <div class="row collapse">
          <div class="small-3 large-1 columns">
            <span class="prefix">
              <i class="fa fa-circle-thin fa-lg seventy-fade"></i>
            </span>
          </div>
          <div class="small-9 large-11 columns">
            <%= form.select("gender",
                           Prospect.gender_choices,
                            {prompt: 'Select Gender'}) %>
          </div>
        </div>
        <div class="row collapse">
          <div class="small-3 large-1 columns">
            <span class="prefix icon-padding">
              <h4 class="seventy-fade">@</h4>
            </span>
          </div>
          <div class="small-9 large-11 columns">
            <%= form.email_field :email, :required => true, placeholder: 'Email' %>
          </div>
        </div>
        <div class="row collapse">
          <div class="small-3 large-1 columns">
            <span class="prefix icon-padding">
              <i class="fa fa-phone fa-2x seventy-fade"></i>
            </span>
          </div>
          <div class="small-9 large-11 columns">
            <%= form.text_field :phone_number,
                                 placeholder: 'Phone Number' %>
          </div>
        </div>
        <div class="row collapse">
          <div class="small-3 large-1 columns">
            <span class="prefix icon-padding">
              <i class="fa fa-skype fa-2x seventy-fade"></i>
            </span>
          </div>
          <div class="small-9 large-11 columns">
            <%= form.text_field :skype, :required => true,
                                 placeholder: 'Skype ID. We will use this for interview' %>
          </div>
        </div>
        <div class="row collapse">
          <div class="small-3 large-1 columns">
            <span class="prefix icon-padding">
              <i class="fa fa-credit-card fa-2x seventy-fade"></i>
            </span>
          </div>
          <div class="small-9 large-11 columns">
            <%= form.select("payment_type",
                           Prospect.payment_types,
                            {prompt: 'Payment Type', :required => true,}) %>
          </div>
        </div>
        <div class="row collapse">
          <div class="small-3 large-1 columns">
            <span class="prefix icon-padding">
              <i class="fa fa-comment fa-2x seventy-fade"></i>
            </span>
          </div>
          <div class="small-9 large-11 columns">
            <%= form.text_area :comment, :rows => 5,
                      placeholder: "Tell us more about your background; What are you looking for from this course" %>
          </div>
        </div>
        <div class="row collapse">
          <%= form.submit "Submit Application", class: "button x2-margin-top" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/prospects/thank_you.html.erb
<% content_for(:title, 'Thank You')%>

<div class="container">
  <div class="row panel white-bg text-center x2-margin-top panel-radius"
        id="thanks-prospect">
    <h1 class="apply-text text-dark-grey">Yay! You are one step closer</h1>
    <p class="">
      What's next?
      We will review your application and schedule an interview with you soon.
      <div class="x2-margin-top">
        Thanks from the VCoder Team.
      </div>
    </p>
  </div>
</div>