config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              :controllers => {
                :omniauth_callbacks => "users/omniauth_callbacks"
              }

  # allow front end angularjs to get current_user and check for user
  devise_scope:user do
    get '/api/current_user' => 'users/sessions#show_current_user'
    post '/api/check/is_user' => 'users/users#is_user', as: 'is_user'
    post '/api/check/is_admin' => 'users/users#is_admin', as: 'is_admin'
  end

  root 'home#index'

  # HANDLE VCODER FRONT
  post 'contact_us' => 'home#contact_us', as: :contact_us
  get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
  get 'faq' => 'home#faq', as: :faq
  get 'tuition' => 'home#tuition', as: :tuition
  get 'curriculum' => 'home#curriculum', as: :curriculum
  get 'the_program' => 'home#the_program', as: :the_program

  resources :prospects do
    collection do
      get :thank_you
    end
  end

  resources :cohorts

  resources :students

  resources :announcements
end

app/views/layouts/angular.html.erb
<!DOCTYPE html>
<html lang="en" data-ng-app="myApp">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VCoder BootCamp" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>
    <div class="fixed top-bar-shadow" ng-controller="pageslideCtrl">
      <nav class="top-bar sticky" data-topbar role="navigation">
        <ul class="title-area">
          <!-- Brand Area -->
          <li class="name">
            <h1>
              <a href="/#/">
                <%= image_tag "white2.png", id: "cr-main-logo", alt: "Vcoder" %>
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="/#/"><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right" id="top-right">
            <li><a href="/#/">DASHBOARD</a>
            <li class="divider"></li>
            <!-- <li class="divider show-for-small"></li>
            <li><a href="<%= the_program_path %>">THE PROGRAM</a> !-->
            <li id="sign-in-li">
              <%= link_to "SIGN OUT",
                           destroy_user_session_path,
                            method: :delete,
                            class: "large button radius",
                            id: "btn-sign-in" %>
            </li>
          </ul>
        </section>
      </nav>
    </div>
    <div class="container">
      <div ng-controller="pageslideCtrl" id="off-canvas-control">
        <a class="button primary btn-off-canvas"
            href="javascript:;"
            ng-click="toggle()"><i class="fa fa-th fa-lg"></i></a>
        <div pageslide ps-open="checked"
              ps-auto-close="true"
              ps-size="240px"
              ps-cloak="false"
              ps-side="left"
              ps-push="true"
              ps-speed="0.5"
              id="div-off-canvas">
          <div id="custom-off-canvas">
            <ul class="no-bullet oc-menu">
              <li>
                <a href="/#/">
                  <i class="cl-blue infi">&infin;</i>
                  <span class="oc-menu-text">DashBoard<span>
                </a>
              </li>
              <li>
                <a href="/#/">
                  <i class="fa fa-user cl-brown"></i>
                  <span class="oc-menu-text">View Profile</span>
                </a>
              </li>
              <li>
                <a href="/#/">
                  <i class="fa fa-rocket cl-green"></i>
                  <span class="oc-menu-text">Help Request</span>
                </a>
              <li>
                <a href="/#/">
                  <i class="fa fa-cog cl-orange"></i>
                  <span class="oc-menu-text">Settings</span>
                </a>
              </li>
             </ul>
             <ul class="no-bullet oc-menu" ng-show="isAdmin()">
              <li>
                <a href="/#/announcements">
                  <i class="fa fa-bullhorn"></i>
                  <span class="oc-menu-text">Announcement<span>
                </a>
              </li>
              <li>
                <a href="/#/students">
                  <i class="fa fa-graduation-cap"></i>
                  <span class="oc-menu-text">Students Accounts</span>
                </a>
              </li>
              <li>
                <a href="/#/">
                  <i class="fa fa-comments-o"></i>
                  <span class="oc-menu-text">Help Request</span>
                </a>
              </li>
              <li>
                <a href="/#/">
                  <i class="fa fa-pencil"></i>
                  <span class="oc-menu-text">Blog</span>
                </a>
              <li>
                <a href="/#/">
                  <i class="fa fa-cog"></i>
                  <span class="oc-menu-text">Settings</span>
                </a>
              </li>
             </ul>
          </div>
        </div>
      </div>
      <div class="marry-weather" data-ng-view></div>
      </div>

    </div> <!-- /container -->
    <div class="small-12 large-12 columns">
      <div id="help-request">
        <button class="button alert hr-btn shake shake-little">
          <i class="fa fa-comments-o hr-icon"></i>
        </button>
      </div>
    <script>
      window.paceOptions = {
        document: true, // disabled
        eventLag: true,
        restartOnPushState: true,
        restartOnRequestAfter: true,
        ajax: {
            trackMethods: [ 'POST','GET']
        }
      };

    </script>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "VCoder BootCamp - Full-Stack Web Development with Ruby on Rails" %></title>
    <%= favicon_link_tag 'favicon.png' %>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="fixed">
      <nav class="top-bar sticky" data-topbar role="navigation">
        <ul class="title-area">
          <!-- Brand Area -->
          <li class="name">
            <h1>
              <a href="/"><%= image_tag "white2.png", id: "main-logo", alt: "Vcoder" %>
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right" id="top-right">
            <li><a href="/">HOME</a>
            <li class="divider"></li>
            <li class="divider show-for-small"></li>
            <li><a href="<%= the_program_path %>">THE PROGRAM</a>
            <li class="divider"></li>
            <li class="divider show-for-small"></li>
            <li><a href="<%= curriculum_path %>">CURRICULUM</a>
            <li class="divider"></li>
            <li class="divider show-for-small"></li>
            <li><a href="<%= tuition_path %>">TUITION</a>
            <li class="divider"></li>
            <li class="divider show-for-small"></li>
            <li><a href="<%= faq_path %>">FAQ</a>
            <li class="divider"></li>
            <li class="divider show-for-small"></li>
            <li id="sign-in-li">
              <a class="large button radius" id="btn-sign-in" href="/users/sign_in">SIGN IN</a>
            </li>
          </ul>
        </section>
      </nav>
    </div>
    <!-- <div class="sub-top"></div> -->
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= yield :extra_javascript %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-63210479-1', 'auto');
      ga('send', 'pageview');

    </script>

    <% unless @unset_footer.present? %>
      <div class="small-12 large-12 columns l-footer m-footer">
        <span class="text-grey">© 2015 VCoder Bootcamp. All rights reserved.</span>
      </div>
    <% end %>
  </body>
</html>